version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - backend

  backend:
    build: .
    command: python backend/weather.py

    volumes:
      - .:/app
    ports:
      - "8080"
